spring:
  application:
    name: library-service
  datasource:
    url: jdbc:postgresql://dpg-cstk168gph6c739firb0-a.oregon-postgres.render.com:5432/person_3hg9
    username: person
    password: 0IBDr2CJjq0ztgV6Nr2N5XY3W4ASdeD1
    driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      format_sql: true
      properties:
        logging:
          level:
            org:
              hibernate:
                SQL: DEBUG
                type:
                  descriptor:
                    sql: TRACE
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8060
logging:
  level:
    org.hibernate.SQL: DEBUG             # 打印SQL语句
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE  # 打印参数绑定

eureka:
  client:
    serviceUrl:
      defaultZone: https://cicd-eureka-server.onrender.com/eureka/
management:
  endpoints:
    web:
      exposure:
        include: health
      base-path: /manage
  endpoint:
    health:
      show-details: always
