version: '3.3'

services:
  eureka-server:
    image: hupengwei123/cicd:eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - microservice-network
    restart: always

  gateway:
    image: hupengwei123/cicd:gateway
    container_name: gateway
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
    networks:
      - microservice-network
    restart: always

  reservation-service:
    image: hupengwei123/cicd:reservation-service
    container_name: reservation-service
    ports:
      - "8070:8070"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
    networks:
      - microservice-network
    restart: always

  library-service:
    image: hupengwei123/cicd:library-service
    container_name: library-service
    ports:
      - "8060:8060"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
    networks:
      - microservice-network
    restart: always

  rating-service:
    image: hupengwei123/cicd:rating-service
    container_name: rating-service
    ports:
      - "8050:8050"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
    networks:
      - microservice-network
    restart: always

# 定义网络
networks:
  microservice-network:
    driver: bridge
