spring:
  application:
    name: rating-service
  datasource:
    url: jdbc:postgresql://dpg-cstk168gph6c739firb0-a.oregon-postgres.render.com:5432/person_3hg9
    username: person
    password: 0IBDr2CJjq0ztgV6Nr2N5XY3W4ASdeD1
    driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8050

eureka:
  client:
    serviceUrl:
      defaultZone: https://cicd-eureka-server.onrender.com/eureka/
  instance:
    hostname: cicd-rating-service.onrender.com
    non-secure-port: 8050
    metadataMap:
      external-url: "https://cicd-rating-service.onrender.com"  # 注册时使用外部 URL
management:
  endpoints:
    web:
      exposure:
        include: health
      base-path: /manage
  endpoint:
    health:
      show-details: always
