spring:
  application:
    name: reservation-service
  datasource:
    url: jdbc:postgresql://dpg-cstk168gph6c739firb0-a.oregon-postgres.render.com:5432/person_3hg9
    username: person
    password: 0IBDr2CJjq0ztgV6Nr2N5XY3W4ASdeD1
    driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8070

eureka:
  client:
    serviceUrl:
      defaultZone: https://cicd-eureka-server.onrender.com/eureka/
  instance:
    hostname: cicd-reservation-service.onrender.com
    non-secure-port: 8070
    metadataMap:
      external-url: "https://cicd-reservation-service.onrender.com"
management:
  endpoints:
    web:
      exposure:
        include: health
      base-path: /manage
  endpoint:
    health:
      show-details: always
