name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build all services
        run: mvn clean package -DskipTests

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 分别构建和推送每个服务的镜像
      - name: Build and push eureka-server
        uses: docker/build-push-action@v3
        with:
          context: ./discovery-service
          push: true
          tags: |
            hupengwei123/cicd:eureka-server

      - name: Build and push gateway
        uses: docker/build-push-action@v3
        with:
          context: ./gateway-service
          push: true
          tags: |
            hupengwei123/cicd:gateway

      - name: Build and push reservation-service
        uses: docker/build-push-action@v3
        with:
          context: ./reservation-service
          push: true
          tags: |
            hupengwei123/cicd:reservation-service
      - name: Build and push library-service
        uses: docker/build-push-action@v3
        with:
          context: ./library-service
          push: true
          tags: |
            hupengwei123/cicd:library-service

      - name: Build and push rating-service
        uses: docker/build-push-action@v3
        with:
          context: ./rating-service
          push: true
          tags: |
            hupengwei123/cicd:rating-service

      # 缓存处理
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd /root   # 修改为你的docker-compose.yml所在目录
            
            # 拉取所有最新镜像并重启所有服务
            docker-compose pull
            docker-compose up -d --force-recreate


      - name: Wait for service to be ready
        run: |
          echo "Waiting for service to start..."
          sleep 180 # 根据实际启动时间调整
      # 运行 Postman API 测试
      - name: Run Postman API Tests
        uses: matt-ball/newman-action@master
        with:
          collection: ./postman/collection.json
          environment: ./postman/environment.json
          delayRequest: 108
          reporters: '[ "cli" ]'