name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build all services
        run: mvn clean package -DskipTests

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 分别构建和推送每个服务的镜像
      - name: Build and push eureka-server
        uses: docker/build-push-action@v3
        with:
          context: ./discovery-service
          push: true
          tags: |
            hupengwei123/cicd:eureka-server
            hupengwei123/cicd:eureka-server-${{ github.sha }}

      - name: Build and push gateway
        uses: docker/build-push-action@v3
        with:
          context: ./gateway-service
          push: true
          tags: |
            hupengwei123/cicd:gateway
            hupengwei123/cicd:gateway-${{ github.sha }}

      - name: Build and push reservation-service
        uses: docker/build-push-action@v3
        with:
          context: ./reservation-service
          push: true
          tags: |
            hupengwei123/cicd:reservation-service
            hupengwei123/cicd:reservation-service-${{ github.sha }}

      - name: Build and push library-service
        uses: docker/build-push-action@v3
        with:
          context: ./library-service
          push: true
          tags: |
            hupengwei123/cicd:library-service
            hupengwei123/cicd:library-service-${{ github.sha }}

      - name: Build and push rating-service
        uses: docker/build-push-action@v3
        with:
          context: ./rating-service
          push: true
          tags: |
            hupengwei123/cicd:rating-service
            hupengwei123/cicd:rating-service-${{ github.sha }}

      # 缓存处理
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
