name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'  # 启用 Maven 缓存

      - name: Build all services
        run: mvn clean package -DskipTests

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        env:
          DOCKER_BUILDKIT: 1
        strategy:
          matrix:
            include:
              - service: eureka-server
                context: ./discovery-service
              - service: gateway
                context: ./gateway-service
              - service: reservation-service
                context: ./reservation-service
              - service: library-service
                context: ./library-service
              - service: rating-service
                context: ./rating-service
        steps:
          - name: Build and push ${{ matrix.service }}
            uses: docker/build-push-action@v3
            with:
              context: ${{ matrix.context }}
              push: true
              tags: |
                hupengwei123/cicd:${{ matrix.service }}
                hupengwei123/cicd:${{ matrix.service }}-${{ github.sha }}
              cache-from: type=local,src=/tmp/.buildx-cache
              cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      # 更新缓存
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
